2025-05-25 23:44:41,025 - errlog - ERROR - Exception type: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x581c00e7971a <unknown>
#1 0x581c0091c0a0 <unknown>
#2 0x581c00922cff <unknown>
#3 0x581c00925578 <unknown>
#4 0x581c00925603 <unknown>
#5 0x581c00967f7d <unknown>
#6 0x581c009933a2 <unknown>
#7 0x581c0096151a <unknown>
#8 0x581c0099356e <unknown>
#9 0x581c009b92a0 <unknown>
#10 0x581c00993173 <unknown>
#11 0x581c0095fd4b <unknown>
#12 0x581c009609b1 <unknown>
#13 0x581c00e3e8cb <unknown>
#14 0x581c00e427ca <unknown>
#15 0x581c00e26622 <unknown>
#16 0x581c00e43354 <unknown>
#17 0x581c00e0b45f <unknown>
#18 0x581c00e674f8 <unknown>
#19 0x581c00e676d6 <unknown>
#20 0x581c00e78586 <unknown>
#21 0x7d29eb09caa4 <unknown>
#22 0x7d29eb129c3c <unknown>
Traceback (most recent call last):
  File "/home/albin/projects/israel/scrapers/aljazeera.py", line 69, in collect_newspage
    strings.append(i.text)
                   ^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 109, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x581c00e7971a <unknown>
#1 0x581c0091c0a0 <unknown>
#2 0x581c00922cff <unknown>
#3 0x581c00925578 <unknown>
#4 0x581c00925603 <unknown>
#5 0x581c00967f7d <unknown>
#6 0x581c009933a2 <unknown>
#7 0x581c0096151a <unknown>
#8 0x581c0099356e <unknown>
#9 0x581c009b92a0 <unknown>
#10 0x581c00993173 <unknown>
#11 0x581c0095fd4b <unknown>
#12 0x581c009609b1 <unknown>
#13 0x581c00e3e8cb <unknown>
#14 0x581c00e427ca <unknown>
#15 0x581c00e26622 <unknown>
#16 0x581c00e43354 <unknown>
#17 0x581c00e0b45f <unknown>
#18 0x581c00e674f8 <unknown>
#19 0x581c00e676d6 <unknown>
#20 0x581c00e78586 <unknown>
#21 0x7d29eb09caa4 <unknown>
#22 0x7d29eb129c3c <unknown>

2025-05-25 23:55:42,714 - errlog - ERROR - Exception type: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x623c9b9ba71a <unknown>
#1 0x623c9b45d0a0 <unknown>
#2 0x623c9b463cff <unknown>
#3 0x623c9b466578 <unknown>
#4 0x623c9b466603 <unknown>
#5 0x623c9b4a8f7d <unknown>
#6 0x623c9b4d43a2 <unknown>
#7 0x623c9b4a251a <unknown>
#8 0x623c9b4d456e <unknown>
#9 0x623c9b4fa2a0 <unknown>
#10 0x623c9b4d4173 <unknown>
#11 0x623c9b4a0d4b <unknown>
#12 0x623c9b4a19b1 <unknown>
#13 0x623c9b97f8cb <unknown>
#14 0x623c9b9837ca <unknown>
#15 0x623c9b967622 <unknown>
#16 0x623c9b984354 <unknown>
#17 0x623c9b94c45f <unknown>
#18 0x623c9b9a84f8 <unknown>
#19 0x623c9b9a86d6 <unknown>
#20 0x623c9b9b9586 <unknown>
#21 0x78c6bec9caa4 <unknown>
#22 0x78c6bed29c3c <unknown>
Traceback (most recent call last):
  File "/home/albin/projects/israel/scrapers/aljazeera.py", line 69, in collect_newspage
    strings.append(i.text)
                   ^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 109, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x623c9b9ba71a <unknown>
#1 0x623c9b45d0a0 <unknown>
#2 0x623c9b463cff <unknown>
#3 0x623c9b466578 <unknown>
#4 0x623c9b466603 <unknown>
#5 0x623c9b4a8f7d <unknown>
#6 0x623c9b4d43a2 <unknown>
#7 0x623c9b4a251a <unknown>
#8 0x623c9b4d456e <unknown>
#9 0x623c9b4fa2a0 <unknown>
#10 0x623c9b4d4173 <unknown>
#11 0x623c9b4a0d4b <unknown>
#12 0x623c9b4a19b1 <unknown>
#13 0x623c9b97f8cb <unknown>
#14 0x623c9b9837ca <unknown>
#15 0x623c9b967622 <unknown>
#16 0x623c9b984354 <unknown>
#17 0x623c9b94c45f <unknown>
#18 0x623c9b9a84f8 <unknown>
#19 0x623c9b9a86d6 <unknown>
#20 0x623c9b9b9586 <unknown>
#21 0x78c6bec9caa4 <unknown>
#22 0x78c6bed29c3c <unknown>

2025-05-25 23:58:54,670 - errlog - ERROR - Exception type: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x5ad2a360571a <unknown>
#1 0x5ad2a30a80a0 <unknown>
#2 0x5ad2a30aecff <unknown>
#3 0x5ad2a30b1578 <unknown>
#4 0x5ad2a30b1603 <unknown>
#5 0x5ad2a30f3f7d <unknown>
#6 0x5ad2a311f3a2 <unknown>
#7 0x5ad2a30ed51a <unknown>
#8 0x5ad2a311f56e <unknown>
#9 0x5ad2a31452a0 <unknown>
#10 0x5ad2a311f173 <unknown>
#11 0x5ad2a30ebd4b <unknown>
#12 0x5ad2a30ec9b1 <unknown>
#13 0x5ad2a35ca8cb <unknown>
#14 0x5ad2a35ce7ca <unknown>
#15 0x5ad2a35b2622 <unknown>
#16 0x5ad2a35cf354 <unknown>
#17 0x5ad2a359745f <unknown>
#18 0x5ad2a35f34f8 <unknown>
#19 0x5ad2a35f36d6 <unknown>
#20 0x5ad2a3604586 <unknown>
#21 0x731df089caa4 <unknown>
#22 0x731df0929c3c <unknown>
Traceback (most recent call last):
  File "/home/albin/projects/israel/scrapers/aljazeera.py", line 69, in collect_newspage
    strings.append(i.text)
                   ^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 109, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x5ad2a360571a <unknown>
#1 0x5ad2a30a80a0 <unknown>
#2 0x5ad2a30aecff <unknown>
#3 0x5ad2a30b1578 <unknown>
#4 0x5ad2a30b1603 <unknown>
#5 0x5ad2a30f3f7d <unknown>
#6 0x5ad2a311f3a2 <unknown>
#7 0x5ad2a30ed51a <unknown>
#8 0x5ad2a311f56e <unknown>
#9 0x5ad2a31452a0 <unknown>
#10 0x5ad2a311f173 <unknown>
#11 0x5ad2a30ebd4b <unknown>
#12 0x5ad2a30ec9b1 <unknown>
#13 0x5ad2a35ca8cb <unknown>
#14 0x5ad2a35ce7ca <unknown>
#15 0x5ad2a35b2622 <unknown>
#16 0x5ad2a35cf354 <unknown>
#17 0x5ad2a359745f <unknown>
#18 0x5ad2a35f34f8 <unknown>
#19 0x5ad2a35f36d6 <unknown>
#20 0x5ad2a3604586 <unknown>
#21 0x731df089caa4 <unknown>
#22 0x731df0929c3c <unknown>

2025-05-26 00:05:17,340 - errlog - ERROR - Exception type: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x5bbb3524d71a <unknown>
#1 0x5bbb34cf00a0 <unknown>
#2 0x5bbb34cf6cff <unknown>
#3 0x5bbb34cf9578 <unknown>
#4 0x5bbb34cf9603 <unknown>
#5 0x5bbb34d3bf7d <unknown>
#6 0x5bbb34d673a2 <unknown>
#7 0x5bbb34d3551a <unknown>
#8 0x5bbb34d6756e <unknown>
#9 0x5bbb34d8d2a0 <unknown>
#10 0x5bbb34d67173 <unknown>
#11 0x5bbb34d33d4b <unknown>
#12 0x5bbb34d349b1 <unknown>
#13 0x5bbb352128cb <unknown>
#14 0x5bbb352167ca <unknown>
#15 0x5bbb351fa622 <unknown>
#16 0x5bbb35217354 <unknown>
#17 0x5bbb351df45f <unknown>
#18 0x5bbb3523b4f8 <unknown>
#19 0x5bbb3523b6d6 <unknown>
#20 0x5bbb3524c586 <unknown>
#21 0x765cc389caa4 <unknown>
#22 0x765cc3929c3c <unknown>
Traceback (most recent call last):
  File "/home/albin/projects/israel/scrapers/aljazeera.py", line 69, in collect_newspage
    strings.append(i.text)
                   ^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 109, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x5bbb3524d71a <unknown>
#1 0x5bbb34cf00a0 <unknown>
#2 0x5bbb34cf6cff <unknown>
#3 0x5bbb34cf9578 <unknown>
#4 0x5bbb34cf9603 <unknown>
#5 0x5bbb34d3bf7d <unknown>
#6 0x5bbb34d673a2 <unknown>
#7 0x5bbb34d3551a <unknown>
#8 0x5bbb34d6756e <unknown>
#9 0x5bbb34d8d2a0 <unknown>
#10 0x5bbb34d67173 <unknown>
#11 0x5bbb34d33d4b <unknown>
#12 0x5bbb34d349b1 <unknown>
#13 0x5bbb352128cb <unknown>
#14 0x5bbb352167ca <unknown>
#15 0x5bbb351fa622 <unknown>
#16 0x5bbb35217354 <unknown>
#17 0x5bbb351df45f <unknown>
#18 0x5bbb3523b4f8 <unknown>
#19 0x5bbb3523b6d6 <unknown>
#20 0x5bbb3524c586 <unknown>
#21 0x765cc389caa4 <unknown>
#22 0x765cc3929c3c <unknown>

2025-05-26 00:39:17,304 - errlog - ERROR - Exception type: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x578ab550371a <unknown>
#1 0x578ab4fa60a0 <unknown>
#2 0x578ab4faccff <unknown>
#3 0x578ab4faf578 <unknown>
#4 0x578ab4faf603 <unknown>
#5 0x578ab4ff1f7d <unknown>
#6 0x578ab501d3a2 <unknown>
#7 0x578ab4feb51a <unknown>
#8 0x578ab501d56e <unknown>
#9 0x578ab50432a0 <unknown>
#10 0x578ab501d173 <unknown>
#11 0x578ab4fe9d4b <unknown>
#12 0x578ab4fea9b1 <unknown>
#13 0x578ab54c88cb <unknown>
#14 0x578ab54cc7ca <unknown>
#15 0x578ab54b0622 <unknown>
#16 0x578ab54cd354 <unknown>
#17 0x578ab549545f <unknown>
#18 0x578ab54f14f8 <unknown>
#19 0x578ab54f16d6 <unknown>
#20 0x578ab5502586 <unknown>
#21 0x7f6c4089caa4 <unknown>
#22 0x7f6c40929c3c <unknown>
Traceback (most recent call last):
  File "/home/albin/projects/israel/scrapers/aljazeera.py", line 69, in collect_newspage
    strings.append(i.text)
                   ^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 109, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x578ab550371a <unknown>
#1 0x578ab4fa60a0 <unknown>
#2 0x578ab4faccff <unknown>
#3 0x578ab4faf578 <unknown>
#4 0x578ab4faf603 <unknown>
#5 0x578ab4ff1f7d <unknown>
#6 0x578ab501d3a2 <unknown>
#7 0x578ab4feb51a <unknown>
#8 0x578ab501d56e <unknown>
#9 0x578ab50432a0 <unknown>
#10 0x578ab501d173 <unknown>
#11 0x578ab4fe9d4b <unknown>
#12 0x578ab4fea9b1 <unknown>
#13 0x578ab54c88cb <unknown>
#14 0x578ab54cc7ca <unknown>
#15 0x578ab54b0622 <unknown>
#16 0x578ab54cd354 <unknown>
#17 0x578ab549545f <unknown>
#18 0x578ab54f14f8 <unknown>
#19 0x578ab54f16d6 <unknown>
#20 0x578ab5502586 <unknown>
#21 0x7f6c4089caa4 <unknown>
#22 0x7f6c40929c3c <unknown>

2025-05-26 01:07:06,695 - errlog - ERROR - Exception type: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x5f7a56d8371a <unknown>
#1 0x5f7a568260a0 <unknown>
#2 0x5f7a5682ccff <unknown>
#3 0x5f7a5682f578 <unknown>
#4 0x5f7a5682f603 <unknown>
#5 0x5f7a56871f7d <unknown>
#6 0x5f7a5689d3a2 <unknown>
#7 0x5f7a5686b51a <unknown>
#8 0x5f7a5689d56e <unknown>
#9 0x5f7a568c32a0 <unknown>
#10 0x5f7a5689d173 <unknown>
#11 0x5f7a56869d4b <unknown>
#12 0x5f7a5686a9b1 <unknown>
#13 0x5f7a56d488cb <unknown>
#14 0x5f7a56d4c7ca <unknown>
#15 0x5f7a56d30622 <unknown>
#16 0x5f7a56d4d354 <unknown>
#17 0x5f7a56d1545f <unknown>
#18 0x5f7a56d714f8 <unknown>
#19 0x5f7a56d716d6 <unknown>
#20 0x5f7a56d82586 <unknown>
#21 0x7932c769caa4 <unknown>
#22 0x7932c7729c3c <unknown>
Traceback (most recent call last):
  File "/home/albin/projects/israel/scrapers/aljazeera.py", line 69, in collect_newspage
    strings.append(i.text)
                   ^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 109, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x5f7a56d8371a <unknown>
#1 0x5f7a568260a0 <unknown>
#2 0x5f7a5682ccff <unknown>
#3 0x5f7a5682f578 <unknown>
#4 0x5f7a5682f603 <unknown>
#5 0x5f7a56871f7d <unknown>
#6 0x5f7a5689d3a2 <unknown>
#7 0x5f7a5686b51a <unknown>
#8 0x5f7a5689d56e <unknown>
#9 0x5f7a568c32a0 <unknown>
#10 0x5f7a5689d173 <unknown>
#11 0x5f7a56869d4b <unknown>
#12 0x5f7a5686a9b1 <unknown>
#13 0x5f7a56d488cb <unknown>
#14 0x5f7a56d4c7ca <unknown>
#15 0x5f7a56d30622 <unknown>
#16 0x5f7a56d4d354 <unknown>
#17 0x5f7a56d1545f <unknown>
#18 0x5f7a56d714f8 <unknown>
#19 0x5f7a56d716d6 <unknown>
#20 0x5f7a56d82586 <unknown>
#21 0x7932c769caa4 <unknown>
#22 0x7932c7729c3c <unknown>

2025-05-26 01:23:53,266 - errlog - ERROR - Exception type: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x599e6e0ed71a <unknown>
#1 0x599e6db900a0 <unknown>
#2 0x599e6db96cff <unknown>
#3 0x599e6db99578 <unknown>
#4 0x599e6db99603 <unknown>
#5 0x599e6dbdbf7d <unknown>
#6 0x599e6dc073a2 <unknown>
#7 0x599e6dbd551a <unknown>
#8 0x599e6dc0756e <unknown>
#9 0x599e6dc2d2a0 <unknown>
#10 0x599e6dc07173 <unknown>
#11 0x599e6dbd3d4b <unknown>
#12 0x599e6dbd49b1 <unknown>
#13 0x599e6e0b28cb <unknown>
#14 0x599e6e0b67ca <unknown>
#15 0x599e6e09a622 <unknown>
#16 0x599e6e0b7354 <unknown>
#17 0x599e6e07f45f <unknown>
#18 0x599e6e0db4f8 <unknown>
#19 0x599e6e0db6d6 <unknown>
#20 0x599e6e0ec586 <unknown>
#21 0x7f84c029caa4 <unknown>
#22 0x7f84c0329c3c <unknown>
Traceback (most recent call last):
  File "/home/albin/projects/israel/scrapers/aljazeera.py", line 69, in collect_newspage
    strings.append(i.text)
                   ^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 109, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x599e6e0ed71a <unknown>
#1 0x599e6db900a0 <unknown>
#2 0x599e6db96cff <unknown>
#3 0x599e6db99578 <unknown>
#4 0x599e6db99603 <unknown>
#5 0x599e6dbdbf7d <unknown>
#6 0x599e6dc073a2 <unknown>
#7 0x599e6dbd551a <unknown>
#8 0x599e6dc0756e <unknown>
#9 0x599e6dc2d2a0 <unknown>
#10 0x599e6dc07173 <unknown>
#11 0x599e6dbd3d4b <unknown>
#12 0x599e6dbd49b1 <unknown>
#13 0x599e6e0b28cb <unknown>
#14 0x599e6e0b67ca <unknown>
#15 0x599e6e09a622 <unknown>
#16 0x599e6e0b7354 <unknown>
#17 0x599e6e07f45f <unknown>
#18 0x599e6e0db4f8 <unknown>
#19 0x599e6e0db6d6 <unknown>
#20 0x599e6e0ec586 <unknown>
#21 0x7f84c029caa4 <unknown>
#22 0x7f84c0329c3c <unknown>

2025-05-26 01:28:43,712 - errlog - ERROR - Exception type: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x62cace80971a <unknown>
#1 0x62cace2ac0a0 <unknown>
#2 0x62cace2b2cff <unknown>
#3 0x62cace2b5578 <unknown>
#4 0x62cace2b5603 <unknown>
#5 0x62cace2f7f7d <unknown>
#6 0x62cace3233a2 <unknown>
#7 0x62cace2f151a <unknown>
#8 0x62cace32356e <unknown>
#9 0x62cace3492a0 <unknown>
#10 0x62cace323173 <unknown>
#11 0x62cace2efd4b <unknown>
#12 0x62cace2f09b1 <unknown>
#13 0x62cace7ce8cb <unknown>
#14 0x62cace7d27ca <unknown>
#15 0x62cace7b6622 <unknown>
#16 0x62cace7d3354 <unknown>
#17 0x62cace79b45f <unknown>
#18 0x62cace7f74f8 <unknown>
#19 0x62cace7f76d6 <unknown>
#20 0x62cace808586 <unknown>
#21 0x78a4b789caa4 <unknown>
#22 0x78a4b7929c3c <unknown>
Traceback (most recent call last):
  File "/home/albin/projects/israel/scrapers/aljazeera.py", line 69, in collect_newspage
    strings.append(i.text)
                   ^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 109, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x62cace80971a <unknown>
#1 0x62cace2ac0a0 <unknown>
#2 0x62cace2b2cff <unknown>
#3 0x62cace2b5578 <unknown>
#4 0x62cace2b5603 <unknown>
#5 0x62cace2f7f7d <unknown>
#6 0x62cace3233a2 <unknown>
#7 0x62cace2f151a <unknown>
#8 0x62cace32356e <unknown>
#9 0x62cace3492a0 <unknown>
#10 0x62cace323173 <unknown>
#11 0x62cace2efd4b <unknown>
#12 0x62cace2f09b1 <unknown>
#13 0x62cace7ce8cb <unknown>
#14 0x62cace7d27ca <unknown>
#15 0x62cace7b6622 <unknown>
#16 0x62cace7d3354 <unknown>
#17 0x62cace79b45f <unknown>
#18 0x62cace7f74f8 <unknown>
#19 0x62cace7f76d6 <unknown>
#20 0x62cace808586 <unknown>
#21 0x78a4b789caa4 <unknown>
#22 0x78a4b7929c3c <unknown>

2025-05-26 01:29:57,319 - errlog - ERROR - Exception type: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x62f0af22171a <unknown>
#1 0x62f0aecc40a0 <unknown>
#2 0x62f0aeccacff <unknown>
#3 0x62f0aeccd578 <unknown>
#4 0x62f0aeccd603 <unknown>
#5 0x62f0aed0ff7d <unknown>
#6 0x62f0aed3b3a2 <unknown>
#7 0x62f0aed0951a <unknown>
#8 0x62f0aed3b56e <unknown>
#9 0x62f0aed612a0 <unknown>
#10 0x62f0aed3b173 <unknown>
#11 0x62f0aed07d4b <unknown>
#12 0x62f0aed089b1 <unknown>
#13 0x62f0af1e68cb <unknown>
#14 0x62f0af1ea7ca <unknown>
#15 0x62f0af1ce622 <unknown>
#16 0x62f0af1eb354 <unknown>
#17 0x62f0af1b345f <unknown>
#18 0x62f0af20f4f8 <unknown>
#19 0x62f0af20f6d6 <unknown>
#20 0x62f0af220586 <unknown>
#21 0x7b5bd189caa4 <unknown>
#22 0x7b5bd1929c3c <unknown>
Traceback (most recent call last):
  File "/home/albin/projects/israel/scrapers/aljazeera.py", line 69, in collect_newspage
    strings.append(i.text)
                   ^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 109, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x62f0af22171a <unknown>
#1 0x62f0aecc40a0 <unknown>
#2 0x62f0aeccacff <unknown>
#3 0x62f0aeccd578 <unknown>
#4 0x62f0aeccd603 <unknown>
#5 0x62f0aed0ff7d <unknown>
#6 0x62f0aed3b3a2 <unknown>
#7 0x62f0aed0951a <unknown>
#8 0x62f0aed3b56e <unknown>
#9 0x62f0aed612a0 <unknown>
#10 0x62f0aed3b173 <unknown>
#11 0x62f0aed07d4b <unknown>
#12 0x62f0aed089b1 <unknown>
#13 0x62f0af1e68cb <unknown>
#14 0x62f0af1ea7ca <unknown>
#15 0x62f0af1ce622 <unknown>
#16 0x62f0af1eb354 <unknown>
#17 0x62f0af1b345f <unknown>
#18 0x62f0af20f4f8 <unknown>
#19 0x62f0af20f6d6 <unknown>
#20 0x62f0af220586 <unknown>
#21 0x7b5bd189caa4 <unknown>
#22 0x7b5bd1929c3c <unknown>

2025-05-26 01:40:27,714 - errlog - ERROR - Exception type: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x563ef8ae271a <unknown>
#1 0x563ef85850a0 <unknown>
#2 0x563ef858bcff <unknown>
#3 0x563ef858e578 <unknown>
#4 0x563ef858e603 <unknown>
#5 0x563ef85d0f7d <unknown>
#6 0x563ef85fc3a2 <unknown>
#7 0x563ef85ca51a <unknown>
#8 0x563ef85fc56e <unknown>
#9 0x563ef86222a0 <unknown>
#10 0x563ef85fc173 <unknown>
#11 0x563ef85c8d4b <unknown>
#12 0x563ef85c99b1 <unknown>
#13 0x563ef8aa78cb <unknown>
#14 0x563ef8aab7ca <unknown>
#15 0x563ef8a8f622 <unknown>
#16 0x563ef8aac354 <unknown>
#17 0x563ef8a7445f <unknown>
#18 0x563ef8ad04f8 <unknown>
#19 0x563ef8ad06d6 <unknown>
#20 0x563ef8ae1586 <unknown>
#21 0x7bf8ff49caa4 <unknown>
#22 0x7bf8ff529c3c <unknown>
Traceback (most recent call last):
  File "/home/albin/projects/israel/scrapers/aljazeera.py", line 69, in collect_newspage
    strings.append(i.text)
                   ^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 109, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x563ef8ae271a <unknown>
#1 0x563ef85850a0 <unknown>
#2 0x563ef858bcff <unknown>
#3 0x563ef858e578 <unknown>
#4 0x563ef858e603 <unknown>
#5 0x563ef85d0f7d <unknown>
#6 0x563ef85fc3a2 <unknown>
#7 0x563ef85ca51a <unknown>
#8 0x563ef85fc56e <unknown>
#9 0x563ef86222a0 <unknown>
#10 0x563ef85fc173 <unknown>
#11 0x563ef85c8d4b <unknown>
#12 0x563ef85c99b1 <unknown>
#13 0x563ef8aa78cb <unknown>
#14 0x563ef8aab7ca <unknown>
#15 0x563ef8a8f622 <unknown>
#16 0x563ef8aac354 <unknown>
#17 0x563ef8a7445f <unknown>
#18 0x563ef8ad04f8 <unknown>
#19 0x563ef8ad06d6 <unknown>
#20 0x563ef8ae1586 <unknown>
#21 0x7bf8ff49caa4 <unknown>
#22 0x7bf8ff529c3c <unknown>

2025-05-26 01:46:38,822 - errlog - ERROR - Exception type: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//header//h1"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x566d4ee9771a <unknown>
#1 0x566d4e93a0a0 <unknown>
#2 0x566d4e98b9b0 <unknown>
#3 0x566d4e98bba1 <unknown>
#4 0x566d4e9d9ea4 <unknown>
#5 0x566d4e9b13cd <unknown>
#6 0x566d4e9d72a0 <unknown>
#7 0x566d4e9b1173 <unknown>
#8 0x566d4e97dd4b <unknown>
#9 0x566d4e97e9b1 <unknown>
#10 0x566d4ee5c8cb <unknown>
#11 0x566d4ee607ca <unknown>
#12 0x566d4ee44622 <unknown>
#13 0x566d4ee61354 <unknown>
#14 0x566d4ee2945f <unknown>
#15 0x566d4ee854f8 <unknown>
#16 0x566d4ee856d6 <unknown>
#17 0x566d4ee96586 <unknown>
#18 0x7bb3b6e9caa4 <unknown>
#19 0x7bb3b6f29c3c <unknown>
Traceback (most recent call last):
  File "/home/albin/projects/israel/scrapers/aljazeera.py", line 64, in collect_newspage
    title = driver.find_element(By.XPATH, '//header//h1').text
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 917, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//header//h1"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x566d4ee9771a <unknown>
#1 0x566d4e93a0a0 <unknown>
#2 0x566d4e98b9b0 <unknown>
#3 0x566d4e98bba1 <unknown>
#4 0x566d4e9d9ea4 <unknown>
#5 0x566d4e9b13cd <unknown>
#6 0x566d4e9d72a0 <unknown>
#7 0x566d4e9b1173 <unknown>
#8 0x566d4e97dd4b <unknown>
#9 0x566d4e97e9b1 <unknown>
#10 0x566d4ee5c8cb <unknown>
#11 0x566d4ee607ca <unknown>
#12 0x566d4ee44622 <unknown>
#13 0x566d4ee61354 <unknown>
#14 0x566d4ee2945f <unknown>
#15 0x566d4ee854f8 <unknown>
#16 0x566d4ee856d6 <unknown>
#17 0x566d4ee96586 <unknown>
#18 0x7bb3b6e9caa4 <unknown>
#19 0x7bb3b6f29c3c <unknown>

2025-05-26 01:54:39,235 - errlog - ERROR - Exception type: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x5e8d0de8971a <unknown>
#1 0x5e8d0d92c0a0 <unknown>
#2 0x5e8d0d932cff <unknown>
#3 0x5e8d0d935578 <unknown>
#4 0x5e8d0d935603 <unknown>
#5 0x5e8d0d977f7d <unknown>
#6 0x5e8d0d9a33a2 <unknown>
#7 0x5e8d0d97151a <unknown>
#8 0x5e8d0d9a356e <unknown>
#9 0x5e8d0d9c92a0 <unknown>
#10 0x5e8d0d9a3173 <unknown>
#11 0x5e8d0d96fd4b <unknown>
#12 0x5e8d0d9709b1 <unknown>
#13 0x5e8d0de4e8cb <unknown>
#14 0x5e8d0de527ca <unknown>
#15 0x5e8d0de36622 <unknown>
#16 0x5e8d0de53354 <unknown>
#17 0x5e8d0de1b45f <unknown>
#18 0x5e8d0de774f8 <unknown>
#19 0x5e8d0de776d6 <unknown>
#20 0x5e8d0de88586 <unknown>
#21 0x7ef719a9caa4 <unknown>
#22 0x7ef719b29c3c <unknown>
Traceback (most recent call last):
  File "/home/albin/projects/israel/scrapers/aljazeera.py", line 69, in collect_newspage
    strings.append(i.text)
                   ^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 109, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x5e8d0de8971a <unknown>
#1 0x5e8d0d92c0a0 <unknown>
#2 0x5e8d0d932cff <unknown>
#3 0x5e8d0d935578 <unknown>
#4 0x5e8d0d935603 <unknown>
#5 0x5e8d0d977f7d <unknown>
#6 0x5e8d0d9a33a2 <unknown>
#7 0x5e8d0d97151a <unknown>
#8 0x5e8d0d9a356e <unknown>
#9 0x5e8d0d9c92a0 <unknown>
#10 0x5e8d0d9a3173 <unknown>
#11 0x5e8d0d96fd4b <unknown>
#12 0x5e8d0d9709b1 <unknown>
#13 0x5e8d0de4e8cb <unknown>
#14 0x5e8d0de527ca <unknown>
#15 0x5e8d0de36622 <unknown>
#16 0x5e8d0de53354 <unknown>
#17 0x5e8d0de1b45f <unknown>
#18 0x5e8d0de774f8 <unknown>
#19 0x5e8d0de776d6 <unknown>
#20 0x5e8d0de88586 <unknown>
#21 0x7ef719a9caa4 <unknown>
#22 0x7ef719b29c3c <unknown>

2025-05-26 01:58:25,773 - errlog - ERROR - Exception type: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="date-simple"]//span[@aria-hidden]"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x58f206d7771a <unknown>
#1 0x58f20681a0a0 <unknown>
#2 0x58f20686b9b0 <unknown>
#3 0x58f20686bba1 <unknown>
#4 0x58f2068b9ea4 <unknown>
#5 0x58f2068913cd <unknown>
#6 0x58f2068b72a0 <unknown>
#7 0x58f206891173 <unknown>
#8 0x58f20685dd4b <unknown>
#9 0x58f20685e9b1 <unknown>
#10 0x58f206d3c8cb <unknown>
#11 0x58f206d407ca <unknown>
#12 0x58f206d24622 <unknown>
#13 0x58f206d41354 <unknown>
#14 0x58f206d0945f <unknown>
#15 0x58f206d654f8 <unknown>
#16 0x58f206d656d6 <unknown>
#17 0x58f206d76586 <unknown>
#18 0x78d32089caa4 <unknown>
#19 0x78d320929c3c <unknown>
Traceback (most recent call last):
  File "/home/albin/projects/israel/scrapers/aljazeera.py", line 65, in collect_newspage
    date_simple = driver.find_element(By.XPATH, '//div[@class="date-simple"]//span[@aria-hidden]').text
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 917, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class="date-simple"]//span[@aria-hidden]"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x58f206d7771a <unknown>
#1 0x58f20681a0a0 <unknown>
#2 0x58f20686b9b0 <unknown>
#3 0x58f20686bba1 <unknown>
#4 0x58f2068b9ea4 <unknown>
#5 0x58f2068913cd <unknown>
#6 0x58f2068b72a0 <unknown>
#7 0x58f206891173 <unknown>
#8 0x58f20685dd4b <unknown>
#9 0x58f20685e9b1 <unknown>
#10 0x58f206d3c8cb <unknown>
#11 0x58f206d407ca <unknown>
#12 0x58f206d24622 <unknown>
#13 0x58f206d41354 <unknown>
#14 0x58f206d0945f <unknown>
#15 0x58f206d654f8 <unknown>
#16 0x58f206d656d6 <unknown>
#17 0x58f206d76586 <unknown>
#18 0x78d32089caa4 <unknown>
#19 0x78d320929c3c <unknown>

2025-05-26 02:00:56,063 - errlog - ERROR - Exception type: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x62e22511671a <unknown>
#1 0x62e224bb90a0 <unknown>
#2 0x62e224bbfcff <unknown>
#3 0x62e224bc2578 <unknown>
#4 0x62e224bc2603 <unknown>
#5 0x62e224c04f7d <unknown>
#6 0x62e224c303a2 <unknown>
#7 0x62e224bfe51a <unknown>
#8 0x62e224c3056e <unknown>
#9 0x62e224c562a0 <unknown>
#10 0x62e224c30173 <unknown>
#11 0x62e224bfcd4b <unknown>
#12 0x62e224bfd9b1 <unknown>
#13 0x62e2250db8cb <unknown>
#14 0x62e2250df7ca <unknown>
#15 0x62e2250c3622 <unknown>
#16 0x62e2250e0354 <unknown>
#17 0x62e2250a845f <unknown>
#18 0x62e2251044f8 <unknown>
#19 0x62e2251046d6 <unknown>
#20 0x62e225115586 <unknown>
#21 0x7d7eb8e9caa4 <unknown>
#22 0x7d7eb8f29c3c <unknown>
Traceback (most recent call last):
  File "/home/albin/projects/israel/scrapers/aljazeera.py", line 69, in collect_newspage
    strings.append(i.text)
                   ^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 109, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x62e22511671a <unknown>
#1 0x62e224bb90a0 <unknown>
#2 0x62e224bbfcff <unknown>
#3 0x62e224bc2578 <unknown>
#4 0x62e224bc2603 <unknown>
#5 0x62e224c04f7d <unknown>
#6 0x62e224c303a2 <unknown>
#7 0x62e224bfe51a <unknown>
#8 0x62e224c3056e <unknown>
#9 0x62e224c562a0 <unknown>
#10 0x62e224c30173 <unknown>
#11 0x62e224bfcd4b <unknown>
#12 0x62e224bfd9b1 <unknown>
#13 0x62e2250db8cb <unknown>
#14 0x62e2250df7ca <unknown>
#15 0x62e2250c3622 <unknown>
#16 0x62e2250e0354 <unknown>
#17 0x62e2250a845f <unknown>
#18 0x62e2251044f8 <unknown>
#19 0x62e2251046d6 <unknown>
#20 0x62e225115586 <unknown>
#21 0x7d7eb8e9caa4 <unknown>
#22 0x7d7eb8f29c3c <unknown>

2025-05-26 02:01:02,878 - errlog - ERROR - Exception type: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x58e88ed6871a <unknown>
#1 0x58e88e80b0a0 <unknown>
#2 0x58e88e811cff <unknown>
#3 0x58e88e814578 <unknown>
#4 0x58e88e814603 <unknown>
#5 0x58e88e856f7d <unknown>
#6 0x58e88e8823a2 <unknown>
#7 0x58e88e85051a <unknown>
#8 0x58e88e88256e <unknown>
#9 0x58e88e8a82a0 <unknown>
#10 0x58e88e882173 <unknown>
#11 0x58e88e84ed4b <unknown>
#12 0x58e88e84f9b1 <unknown>
#13 0x58e88ed2d8cb <unknown>
#14 0x58e88ed317ca <unknown>
#15 0x58e88ed15622 <unknown>
#16 0x58e88ed32354 <unknown>
#17 0x58e88ecfa45f <unknown>
#18 0x58e88ed564f8 <unknown>
#19 0x58e88ed566d6 <unknown>
#20 0x58e88ed67586 <unknown>
#21 0x7ebcba69caa4 <unknown>
#22 0x7ebcba729c3c <unknown>
Traceback (most recent call last):
  File "/home/albin/projects/israel/scrapers/aljazeera.py", line 69, in collect_newspage
    strings.append(i.text)
                   ^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 109, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x58e88ed6871a <unknown>
#1 0x58e88e80b0a0 <unknown>
#2 0x58e88e811cff <unknown>
#3 0x58e88e814578 <unknown>
#4 0x58e88e814603 <unknown>
#5 0x58e88e856f7d <unknown>
#6 0x58e88e8823a2 <unknown>
#7 0x58e88e85051a <unknown>
#8 0x58e88e88256e <unknown>
#9 0x58e88e8a82a0 <unknown>
#10 0x58e88e882173 <unknown>
#11 0x58e88e84ed4b <unknown>
#12 0x58e88e84f9b1 <unknown>
#13 0x58e88ed2d8cb <unknown>
#14 0x58e88ed317ca <unknown>
#15 0x58e88ed15622 <unknown>
#16 0x58e88ed32354 <unknown>
#17 0x58e88ecfa45f <unknown>
#18 0x58e88ed564f8 <unknown>
#19 0x58e88ed566d6 <unknown>
#20 0x58e88ed67586 <unknown>
#21 0x7ebcba69caa4 <unknown>
#22 0x7ebcba729c3c <unknown>

2025-05-26 02:12:35,900 - errlog - ERROR - Exception type: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//header//h1"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x5ec51efe371a <unknown>
#1 0x5ec51ea860a0 <unknown>
#2 0x5ec51ead79b0 <unknown>
#3 0x5ec51ead7ba1 <unknown>
#4 0x5ec51eb25ea4 <unknown>
#5 0x5ec51eafd3cd <unknown>
#6 0x5ec51eb232a0 <unknown>
#7 0x5ec51eafd173 <unknown>
#8 0x5ec51eac9d4b <unknown>
#9 0x5ec51eaca9b1 <unknown>
#10 0x5ec51efa88cb <unknown>
#11 0x5ec51efac7ca <unknown>
#12 0x5ec51ef90622 <unknown>
#13 0x5ec51efad354 <unknown>
#14 0x5ec51ef7545f <unknown>
#15 0x5ec51efd14f8 <unknown>
#16 0x5ec51efd16d6 <unknown>
#17 0x5ec51efe2586 <unknown>
#18 0x75793549caa4 <unknown>
#19 0x757935529c3c <unknown>
Traceback (most recent call last):
  File "/home/albin/projects/israel/scrapers/aljazeera.py", line 64, in collect_newspage
    title = driver.find_element(By.XPATH, '//header//h1').text
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 917, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//header//h1"}
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x5ec51efe371a <unknown>
#1 0x5ec51ea860a0 <unknown>
#2 0x5ec51ead79b0 <unknown>
#3 0x5ec51ead7ba1 <unknown>
#4 0x5ec51eb25ea4 <unknown>
#5 0x5ec51eafd3cd <unknown>
#6 0x5ec51eb232a0 <unknown>
#7 0x5ec51eafd173 <unknown>
#8 0x5ec51eac9d4b <unknown>
#9 0x5ec51eaca9b1 <unknown>
#10 0x5ec51efa88cb <unknown>
#11 0x5ec51efac7ca <unknown>
#12 0x5ec51ef90622 <unknown>
#13 0x5ec51efad354 <unknown>
#14 0x5ec51ef7545f <unknown>
#15 0x5ec51efd14f8 <unknown>
#16 0x5ec51efd16d6 <unknown>
#17 0x5ec51efe2586 <unknown>
#18 0x75793549caa4 <unknown>
#19 0x757935529c3c <unknown>

2025-05-26 02:14:55,352 - errlog - ERROR - Exception type: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x5c91fc53371a <unknown>
#1 0x5c91fbfd60a0 <unknown>
#2 0x5c91fbfdccff <unknown>
#3 0x5c91fbfdf578 <unknown>
#4 0x5c91fbfdf603 <unknown>
#5 0x5c91fc021f7d <unknown>
#6 0x5c91fc04d3a2 <unknown>
#7 0x5c91fc01b51a <unknown>
#8 0x5c91fc04d56e <unknown>
#9 0x5c91fc0732a0 <unknown>
#10 0x5c91fc04d173 <unknown>
#11 0x5c91fc019d4b <unknown>
#12 0x5c91fc01a9b1 <unknown>
#13 0x5c91fc4f88cb <unknown>
#14 0x5c91fc4fc7ca <unknown>
#15 0x5c91fc4e0622 <unknown>
#16 0x5c91fc4fd354 <unknown>
#17 0x5c91fc4c545f <unknown>
#18 0x5c91fc5214f8 <unknown>
#19 0x5c91fc5216d6 <unknown>
#20 0x5c91fc532586 <unknown>
#21 0x743da149caa4 <unknown>
#22 0x743da1529c3c <unknown>
Traceback (most recent call last):
  File "/home/albin/projects/israel/scrapers/aljazeera.py", line 69, in collect_newspage
    strings.append(i.text)
                   ^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 109, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x5c91fc53371a <unknown>
#1 0x5c91fbfd60a0 <unknown>
#2 0x5c91fbfdccff <unknown>
#3 0x5c91fbfdf578 <unknown>
#4 0x5c91fbfdf603 <unknown>
#5 0x5c91fc021f7d <unknown>
#6 0x5c91fc04d3a2 <unknown>
#7 0x5c91fc01b51a <unknown>
#8 0x5c91fc04d56e <unknown>
#9 0x5c91fc0732a0 <unknown>
#10 0x5c91fc04d173 <unknown>
#11 0x5c91fc019d4b <unknown>
#12 0x5c91fc01a9b1 <unknown>
#13 0x5c91fc4f88cb <unknown>
#14 0x5c91fc4fc7ca <unknown>
#15 0x5c91fc4e0622 <unknown>
#16 0x5c91fc4fd354 <unknown>
#17 0x5c91fc4c545f <unknown>
#18 0x5c91fc5214f8 <unknown>
#19 0x5c91fc5216d6 <unknown>
#20 0x5c91fc532586 <unknown>
#21 0x743da149caa4 <unknown>
#22 0x743da1529c3c <unknown>

2025-05-26 02:18:22,293 - errlog - ERROR - Exception type: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x61b20061171a <unknown>
#1 0x61b2000b40a0 <unknown>
#2 0x61b2000bacff <unknown>
#3 0x61b2000bd578 <unknown>
#4 0x61b2000bd603 <unknown>
#5 0x61b2000fff7d <unknown>
#6 0x61b20012b3a2 <unknown>
#7 0x61b2000f951a <unknown>
#8 0x61b20012b56e <unknown>
#9 0x61b2001512a0 <unknown>
#10 0x61b20012b173 <unknown>
#11 0x61b2000f7d4b <unknown>
#12 0x61b2000f89b1 <unknown>
#13 0x61b2005d68cb <unknown>
#14 0x61b2005da7ca <unknown>
#15 0x61b2005be622 <unknown>
#16 0x61b2005db354 <unknown>
#17 0x61b2005a345f <unknown>
#18 0x61b2005ff4f8 <unknown>
#19 0x61b2005ff6d6 <unknown>
#20 0x61b200610586 <unknown>
#21 0x72b8a4c9caa4 <unknown>
#22 0x72b8a4d29c3c <unknown>
Traceback (most recent call last):
  File "/home/albin/projects/israel/scrapers/aljazeera.py", line 69, in collect_newspage
    strings.append(i.text)
                   ^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 109, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x61b20061171a <unknown>
#1 0x61b2000b40a0 <unknown>
#2 0x61b2000bacff <unknown>
#3 0x61b2000bd578 <unknown>
#4 0x61b2000bd603 <unknown>
#5 0x61b2000fff7d <unknown>
#6 0x61b20012b3a2 <unknown>
#7 0x61b2000f951a <unknown>
#8 0x61b20012b56e <unknown>
#9 0x61b2001512a0 <unknown>
#10 0x61b20012b173 <unknown>
#11 0x61b2000f7d4b <unknown>
#12 0x61b2000f89b1 <unknown>
#13 0x61b2005d68cb <unknown>
#14 0x61b2005da7ca <unknown>
#15 0x61b2005be622 <unknown>
#16 0x61b2005db354 <unknown>
#17 0x61b2005a345f <unknown>
#18 0x61b2005ff4f8 <unknown>
#19 0x61b2005ff6d6 <unknown>
#20 0x61b200610586 <unknown>
#21 0x72b8a4c9caa4 <unknown>
#22 0x72b8a4d29c3c <unknown>

2025-05-26 02:27:53,875 - errlog - ERROR - Exception type: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x623df5ccc71a <unknown>
#1 0x623df576f0a0 <unknown>
#2 0x623df5775cff <unknown>
#3 0x623df5778578 <unknown>
#4 0x623df5778603 <unknown>
#5 0x623df57baf7d <unknown>
#6 0x623df57e63a2 <unknown>
#7 0x623df57b451a <unknown>
#8 0x623df57e656e <unknown>
#9 0x623df580c2a0 <unknown>
#10 0x623df57e6173 <unknown>
#11 0x623df57b2d4b <unknown>
#12 0x623df57b39b1 <unknown>
#13 0x623df5c918cb <unknown>
#14 0x623df5c957ca <unknown>
#15 0x623df5c79622 <unknown>
#16 0x623df5c96354 <unknown>
#17 0x623df5c5e45f <unknown>
#18 0x623df5cba4f8 <unknown>
#19 0x623df5cba6d6 <unknown>
#20 0x623df5ccb586 <unknown>
#21 0x72561ea9caa4 <unknown>
#22 0x72561eb29c3c <unknown>
Traceback (most recent call last):
  File "/home/albin/projects/israel/scrapers/aljazeera.py", line 69, in collect_newspage
    strings.append(i.text)
                   ^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 109, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x623df5ccc71a <unknown>
#1 0x623df576f0a0 <unknown>
#2 0x623df5775cff <unknown>
#3 0x623df5778578 <unknown>
#4 0x623df5778603 <unknown>
#5 0x623df57baf7d <unknown>
#6 0x623df57e63a2 <unknown>
#7 0x623df57b451a <unknown>
#8 0x623df57e656e <unknown>
#9 0x623df580c2a0 <unknown>
#10 0x623df57e6173 <unknown>
#11 0x623df57b2d4b <unknown>
#12 0x623df57b39b1 <unknown>
#13 0x623df5c918cb <unknown>
#14 0x623df5c957ca <unknown>
#15 0x623df5c79622 <unknown>
#16 0x623df5c96354 <unknown>
#17 0x623df5c5e45f <unknown>
#18 0x623df5cba4f8 <unknown>
#19 0x623df5cba6d6 <unknown>
#20 0x623df5ccb586 <unknown>
#21 0x72561ea9caa4 <unknown>
#22 0x72561eb29c3c <unknown>

2025-05-26 02:34:15,301 - errlog - ERROR - Exception type: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x5dcca146071a <unknown>
#1 0x5dcca0f030a0 <unknown>
#2 0x5dcca0f09cff <unknown>
#3 0x5dcca0f0c578 <unknown>
#4 0x5dcca0f0c603 <unknown>
#5 0x5dcca0f4ef7d <unknown>
#6 0x5dcca0f7a3a2 <unknown>
#7 0x5dcca0f4851a <unknown>
#8 0x5dcca0f7a56e <unknown>
#9 0x5dcca0fa02a0 <unknown>
#10 0x5dcca0f7a173 <unknown>
#11 0x5dcca0f46d4b <unknown>
#12 0x5dcca0f479b1 <unknown>
#13 0x5dcca14258cb <unknown>
#14 0x5dcca14297ca <unknown>
#15 0x5dcca140d622 <unknown>
#16 0x5dcca142a354 <unknown>
#17 0x5dcca13f245f <unknown>
#18 0x5dcca144e4f8 <unknown>
#19 0x5dcca144e6d6 <unknown>
#20 0x5dcca145f586 <unknown>
#21 0x702be729caa4 <unknown>
#22 0x702be7329c3c <unknown>
Traceback (most recent call last):
  File "/home/albin/projects/israel/scrapers/aljazeera.py", line 69, in collect_newspage
    strings.append(i.text)
                   ^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 109, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x5dcca146071a <unknown>
#1 0x5dcca0f030a0 <unknown>
#2 0x5dcca0f09cff <unknown>
#3 0x5dcca0f0c578 <unknown>
#4 0x5dcca0f0c603 <unknown>
#5 0x5dcca0f4ef7d <unknown>
#6 0x5dcca0f7a3a2 <unknown>
#7 0x5dcca0f4851a <unknown>
#8 0x5dcca0f7a56e <unknown>
#9 0x5dcca0fa02a0 <unknown>
#10 0x5dcca0f7a173 <unknown>
#11 0x5dcca0f46d4b <unknown>
#12 0x5dcca0f479b1 <unknown>
#13 0x5dcca14258cb <unknown>
#14 0x5dcca14297ca <unknown>
#15 0x5dcca140d622 <unknown>
#16 0x5dcca142a354 <unknown>
#17 0x5dcca13f245f <unknown>
#18 0x5dcca144e4f8 <unknown>
#19 0x5dcca144e6d6 <unknown>
#20 0x5dcca145f586 <unknown>
#21 0x702be729caa4 <unknown>
#22 0x702be7329c3c <unknown>

2025-05-26 02:49:30,778 - errlog - ERROR - Exception type: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x653a16c4f71a <unknown>
#1 0x653a166f20a0 <unknown>
#2 0x653a166f8cff <unknown>
#3 0x653a166fb578 <unknown>
#4 0x653a166fb603 <unknown>
#5 0x653a1673df7d <unknown>
#6 0x653a167693a2 <unknown>
#7 0x653a1673751a <unknown>
#8 0x653a1676956e <unknown>
#9 0x653a1678f2a0 <unknown>
#10 0x653a16769173 <unknown>
#11 0x653a16735d4b <unknown>
#12 0x653a167369b1 <unknown>
#13 0x653a16c148cb <unknown>
#14 0x653a16c187ca <unknown>
#15 0x653a16bfc622 <unknown>
#16 0x653a16c19354 <unknown>
#17 0x653a16be145f <unknown>
#18 0x653a16c3d4f8 <unknown>
#19 0x653a16c3d6d6 <unknown>
#20 0x653a16c4e586 <unknown>
#21 0x7a291969caa4 <unknown>
#22 0x7a2919729c3c <unknown>
Traceback (most recent call last):
  File "/home/albin/projects/israel/scrapers/aljazeera.py", line 69, in collect_newspage
    strings.append(i.text)
                   ^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 109, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x653a16c4f71a <unknown>
#1 0x653a166f20a0 <unknown>
#2 0x653a166f8cff <unknown>
#3 0x653a166fb578 <unknown>
#4 0x653a166fb603 <unknown>
#5 0x653a1673df7d <unknown>
#6 0x653a167693a2 <unknown>
#7 0x653a1673751a <unknown>
#8 0x653a1676956e <unknown>
#9 0x653a1678f2a0 <unknown>
#10 0x653a16769173 <unknown>
#11 0x653a16735d4b <unknown>
#12 0x653a167369b1 <unknown>
#13 0x653a16c148cb <unknown>
#14 0x653a16c187ca <unknown>
#15 0x653a16bfc622 <unknown>
#16 0x653a16c19354 <unknown>
#17 0x653a16be145f <unknown>
#18 0x653a16c3d4f8 <unknown>
#19 0x653a16c3d6d6 <unknown>
#20 0x653a16c4e586 <unknown>
#21 0x7a291969caa4 <unknown>
#22 0x7a2919729c3c <unknown>

2025-05-26 03:02:00,154 - errlog - ERROR - Exception type: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x5da34fc7871a <unknown>
#1 0x5da34f71b0a0 <unknown>
#2 0x5da34f721cff <unknown>
#3 0x5da34f724578 <unknown>
#4 0x5da34f724603 <unknown>
#5 0x5da34f766f7d <unknown>
#6 0x5da34f7923a2 <unknown>
#7 0x5da34f76051a <unknown>
#8 0x5da34f79256e <unknown>
#9 0x5da34f7b82a0 <unknown>
#10 0x5da34f792173 <unknown>
#11 0x5da34f75ed4b <unknown>
#12 0x5da34f75f9b1 <unknown>
#13 0x5da34fc3d8cb <unknown>
#14 0x5da34fc417ca <unknown>
#15 0x5da34fc25622 <unknown>
#16 0x5da34fc42354 <unknown>
#17 0x5da34fc0a45f <unknown>
#18 0x5da34fc664f8 <unknown>
#19 0x5da34fc666d6 <unknown>
#20 0x5da34fc77586 <unknown>
#21 0x7aec08c9caa4 <unknown>
#22 0x7aec08d29c3c <unknown>
Traceback (most recent call last):
  File "/home/albin/projects/israel/scrapers/aljazeera.py", line 69, in collect_newspage
    strings.append(i.text)
                   ^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 109, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x5da34fc7871a <unknown>
#1 0x5da34f71b0a0 <unknown>
#2 0x5da34f721cff <unknown>
#3 0x5da34f724578 <unknown>
#4 0x5da34f724603 <unknown>
#5 0x5da34f766f7d <unknown>
#6 0x5da34f7923a2 <unknown>
#7 0x5da34f76051a <unknown>
#8 0x5da34f79256e <unknown>
#9 0x5da34f7b82a0 <unknown>
#10 0x5da34f792173 <unknown>
#11 0x5da34f75ed4b <unknown>
#12 0x5da34f75f9b1 <unknown>
#13 0x5da34fc3d8cb <unknown>
#14 0x5da34fc417ca <unknown>
#15 0x5da34fc25622 <unknown>
#16 0x5da34fc42354 <unknown>
#17 0x5da34fc0a45f <unknown>
#18 0x5da34fc664f8 <unknown>
#19 0x5da34fc666d6 <unknown>
#20 0x5da34fc77586 <unknown>
#21 0x7aec08c9caa4 <unknown>
#22 0x7aec08d29c3c <unknown>

2025-05-26 03:18:10,713 - errlog - ERROR - Exception type: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x6323d3de471a <unknown>
#1 0x6323d38870a0 <unknown>
#2 0x6323d388dcff <unknown>
#3 0x6323d3890578 <unknown>
#4 0x6323d3890603 <unknown>
#5 0x6323d38d2f7d <unknown>
#6 0x6323d38fe3a2 <unknown>
#7 0x6323d38cc51a <unknown>
#8 0x6323d38fe56e <unknown>
#9 0x6323d39242a0 <unknown>
#10 0x6323d38fe173 <unknown>
#11 0x6323d38cad4b <unknown>
#12 0x6323d38cb9b1 <unknown>
#13 0x6323d3da98cb <unknown>
#14 0x6323d3dad7ca <unknown>
#15 0x6323d3d91622 <unknown>
#16 0x6323d3dae354 <unknown>
#17 0x6323d3d7645f <unknown>
#18 0x6323d3dd24f8 <unknown>
#19 0x6323d3dd26d6 <unknown>
#20 0x6323d3de3586 <unknown>
#21 0x7d75bd89caa4 <unknown>
#22 0x7d75bd929c3c <unknown>
Traceback (most recent call last):
  File "/home/albin/projects/israel/scrapers/aljazeera.py", line 69, in collect_newspage
    strings.append(i.text)
                   ^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 109, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 572, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 448, in execute
    self.error_handler.check_response(response)
  File "/home/albin/projects/israel/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=136.0.7103.59); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
#0 0x6323d3de471a <unknown>
#1 0x6323d38870a0 <unknown>
#2 0x6323d388dcff <unknown>
#3 0x6323d3890578 <unknown>
#4 0x6323d3890603 <unknown>
#5 0x6323d38d2f7d <unknown>
#6 0x6323d38fe3a2 <unknown>
#7 0x6323d38cc51a <unknown>
#8 0x6323d38fe56e <unknown>
#9 0x6323d39242a0 <unknown>
#10 0x6323d38fe173 <unknown>
#11 0x6323d38cad4b <unknown>
#12 0x6323d38cb9b1 <unknown>
#13 0x6323d3da98cb <unknown>
#14 0x6323d3dad7ca <unknown>
#15 0x6323d3d91622 <unknown>
#16 0x6323d3dae354 <unknown>
#17 0x6323d3d7645f <unknown>
#18 0x6323d3dd24f8 <unknown>
#19 0x6323d3dd26d6 <unknown>
#20 0x6323d3de3586 <unknown>
#21 0x7d75bd89caa4 <unknown>
#22 0x7d75bd929c3c <unknown>

